"""
Query Understanding Engine.

Parses a natural language query like "restaurants in Lahore" into structured intent.
Uses keyword heuristics — no paid LLM or NLP API required.
"""
import re
from dataclasses import dataclass, field
from typing import List

ENTITY_TYPES = [
    # ── Food & Drink ──────────────────────────────────────────────────────────
    ("restaurant",      ["restaurant", "restaurants", "dining", "eatery", "eateries",
                         "food", "cuisine", "diner", "bistro", "brasserie"],
                        ["amenity=restaurant"]),
    ("cafe",            ["cafe", "coffee shop", "coffee house", "tea house", "tea cafe",
                         "bakery cafe", "cafeteria", "canteen"],
                        ["amenity=cafe"]),
    ("bar",             ["bar", "pub", "lounge", "tavern", "beer garden",
                         "biergarten", "cocktail bar", "wine bar", "sports bar"],
                        ["amenity=bar", "amenity=pub"]),
    ("fast food",       ["fast food", "burger", "fried chicken", "takeaway", "take away",
                         "takeout", "drive through", "drive-through"],
                        ["amenity=fast_food"]),
    ("bakery",          ["bakery", "bakeries", "bread", "patisserie", "pastry shop",
                         "confectionery", "cake shop", "sweet shop"],
                        ["shop=bakery"]),
    ("ice cream shop",  ["ice cream", "gelato", "frozen yogurt", "dessert shop",
                         "desserts", "creamery"],
                        ["amenity=ice_cream", "shop=ice_cream"]),
    ("juice bar",       ["juice bar", "juice shop", "smoothie", "smoothies"],
                        ["amenity=juice_bar", "shop=juice_bar"]),
    ("food court",      ["food court", "food hall", "food market", "food plaza"],
                        ["amenity=food_court"]),
    ("seafood restaurant", ["seafood", "fish restaurant", "sushi", "oyster bar"],
                        ["amenity=restaurant"]),
    ("winery",          ["winery", "winery", "wine cellar", "vineyard", "wine producer"],
                        ["craft=winery", "amenity=winery"]),
    ("brewery",         ["brewery", "breweries", "craft beer", "microbrewery"],
                        ["craft=brewery", "industrial=brewery"]),
    ("distillery",      ["distillery", "distilleries", "spirits producer", "whisky", "whiskey"],
                        ["craft=distillery"]),

    # ── Health & Medical ──────────────────────────────────────────────────────
    ("hospital",        ["hospital", "medical center", "healthcare", "health center",
                         "medical centre", "health complex"],
                        ["amenity=hospital"]),
    ("clinic",          ["clinic", "medical clinic", "health clinic", "polyclinic",
                         "outpatient", "medical office"],
                        ["amenity=clinic"]),
    ("dentist",         ["dentist", "dental", "dental clinic", "orthodontist",
                         "dental surgery"],
                        ["amenity=dentist"]),
    ("pharmacy",        ["pharmacy", "drugstore", "chemist", "medicine shop",
                         "drug store", "medical store"],
                        ["amenity=pharmacy"]),
    ("veterinary clinic", ["vet", "veterinary", "veterinarian", "animal clinic",
                           "animal hospital", "pet clinic"],
                        ["amenity=veterinary"]),
    ("optician",        ["optician", "optometrist", "opticians", "eye clinic",
                         "eyewear", "glasses shop", "spectacles", "ophthalmologist"],
                        ["shop=optician", "healthcare=optometrist"]),
    ("physiotherapy",   ["physiotherapy", "physiotherapist", "physio", "physical therapy",
                         "rehabilitation", "rehab center"],
                        ["healthcare=physiotherapist"]),
    ("mental health",   ["mental health", "psychologist", "psychiatrist", "therapist",
                         "counseling", "counselling", "psychotherapy"],
                        ["healthcare=psychotherapist", "healthcare=psychologist"]),
    ("medical laboratory", ["laboratory", "lab", "pathology lab", "diagnostic lab",
                            "diagnostic center", "blood test", "medical lab"],
                        ["healthcare=laboratory"]),
    ("gym",             ["gym", "fitness center", "fitness centre", "fitness club",
                         "workout", "crossfit", "health club", "bodybuilding gym"],
                        ["leisure=fitness_centre"]),
    ("yoga studio",     ["yoga", "yoga studio", "yoga center", "yoga class",
                         "pilates", "pilates studio", "meditation center"],
                        ["sport=yoga", "leisure=yoga"]),
    ("spa",             ["spa", "wellness center", "wellness centre", "beauty spa",
                         "day spa", "massage spa", "health spa"],
                        ["leisure=spa", "amenity=spa"]),
    ("massage center",  ["massage", "massage center", "massage therapy",
                         "massage parlour", "massage parlor", "body massage"],
                        ["amenity=massage"]),
    ("nursing home",    ["nursing home", "care home", "old age home", "elderly care",
                         "senior living", "assisted living", "retirement home"],
                        ["amenity=nursing_home", "social_facility=nursing_home"]),
    ("dialysis center", ["dialysis", "dialysis center", "kidney dialysis"],
                        ["healthcare=dialysis"]),

    # ── Education ─────────────────────────────────────────────────────────────
    ("school",          ["school", "primary school", "secondary school", "high school",
                         "middle school", "grammar school", "academy"],
                        ["amenity=school"]),
    ("university",      ["university", "universities", "college", "higher education",
                         "institute of technology", "polytechnic"],
                        ["amenity=university", "amenity=college"]),
    ("kindergarten",    ["kindergarten", "preschool", "pre-school", "nursery school",
                         "nursery", "daycare", "day care", "creche", "montessori"],
                        ["amenity=kindergarten"]),
    ("language school", ["language school", "english school", "language institute",
                         "language academy", "english academy", "ielts", "toefl center"],
                        ["amenity=language_school"]),
    ("driving school",  ["driving school", "driving academy", "driver training",
                         "driving lessons", "driving institute"],
                        ["amenity=driving_school"]),
    ("music school",    ["music school", "music academy", "music institute",
                         "music lessons", "guitar school", "piano lessons"],
                        ["amenity=music_school"]),
    ("art school",      ["art school", "art institute", "fine arts", "arts academy",
                         "painting school", "art studio"],
                        ["amenity=art_school"]),
    ("dance school",    ["dance school", "dance studio", "dance academy",
                         "dance classes", "ballet school", "dance institute"],
                        ["leisure=dance"]),
    ("martial arts",    ["martial arts", "karate", "taekwondo", "judo", "boxing gym",
                         "mma gym", "kung fu", "jiu jitsu", "kickboxing",
                         "self defense", "wrestling"],
                        ["sport=martial_arts", "sport=boxing", "sport=judo",
                         "sport=karate", "sport=taekwondo"]),
    ("vocational school", ["vocational school", "technical school", "trade school",
                           "technical institute", "vocational training",
                           "skills training", "polytechnic"],
                          ["amenity=college"]),
    ("tutoring center", ["tutoring", "tutor", "tutoring center", "coaching center",
                         "coaching institute", "academy", "prep school",
                         "exam prep", "learning center"],
                        ["amenity=tutoring_centre"]),
    ("sports academy",  ["sports academy", "cricket academy", "football academy",
                         "sports school", "sports club"],
                        ["leisure=sports_centre"]),
    ("library",         ["library", "public library", "book library"],
                        ["amenity=library"]),

    # ── Accommodation ─────────────────────────────────────────────────────────
    ("hotel",           ["hotel", "hotels", "resort", "inn", "lodge", "motel",
                         "boutique hotel"],
                        ["tourism=hotel", "tourism=motel"]),
    ("hostel",          ["hostel", "guesthouse", "guest house", "bed and breakfast",
                         "b&b", "backpacker"],
                        ["tourism=hostel", "tourism=guest_house"]),
    ("resort",          ["resort", "beach resort", "mountain resort", "spa resort",
                         "holiday resort", "eco resort"],
                        ["tourism=resort"]),
    ("camping",         ["camping", "campsite", "camp site", "caravan park",
                         "rv park", "glamping"],
                        ["tourism=camp_site", "tourism=caravan_site"]),
    ("serviced apartment", ["serviced apartment", "service apartment", "aparthotel",
                            "apart hotel", "extended stay"],
                           ["tourism=apartment"]),

    # ── Tech & Business ───────────────────────────────────────────────────────
    ("startup",          ["startup", "startups", "tech startup", "tech startups",
                          "saas", "saas company", "saas companies",
                          "fintech", "edtech", "healthtech", "ai startup",
                          "early stage", "seed stage", "seed funded",
                          "vc backed", "venture backed", "venture funded",
                          "new business", "new businesses"],
                         ["office=company", "office=it"]),
    ("software company", ["software company", "software companies", "tech company",
                          "tech companies", "it company", "software house",
                          "software houses", "software firm"],
                         ["office=it", "office=company"]),
    ("data center",     ["data center", "data centre", "datacenter", "colocation",
                         "server farm", "hosting"],
                        ["office=it", "building=data_center"]),
    ("law firm",        ["law firm", "law office", "lawyers", "attorney", "solicitors",
                         "legal firm", "legal services", "advocate"],
                        ["office=lawyer", "office=law_firm"]),
    ("accounting firm", ["accounting firm", "accountants", "cpa", "audit firm",
                         "chartered accountants", "ca firm", "tax consultant",
                         "bookkeeping"],
                        ["office=accountant"]),
    ("coworking space", ["coworking", "co-working", "shared office", "work space",
                         "shared workspace", "business center", "business centre",
                         "incubator", "accelerator"],
                        ["office=coworking"]),
    ("digital marketing agency", ["digital marketing", "seo agency", "social media agency",
                                  "marketing agency", "advertising agency", "ad agency",
                                  "media agency", "content agency"],
                                 ["office=company"]),
    ("call center",     ["call center", "call centre", "bpo", "business process outsourcing",
                         "customer support", "customer service center"],
                        ["office=company"]),
    ("consulting firm", ["consulting", "consultant", "consultancy", "management consulting",
                         "business consulting", "advisory firm"],
                        ["office=consulting"]),
    ("insurance company", ["insurance", "insurer", "insurance company", "insurance agency",
                           "insurance broker"],
                          ["office=insurance"]),
    ("investment firm", ["investment", "investment firm", "investment bank",
                         "asset management", "fund", "hedge fund", "private equity",
                         "venture capital", "stock broker"],
                        ["office=financial"]),
    ("architecture firm", ["architect", "architects", "architecture firm",
                            "architecture studio", "interior design"],
                          ["office=architect"]),
    ("engineering firm", ["engineering", "engineering firm", "civil engineering",
                          "structural engineering", "mechanical engineering"],
                         ["office=engineer"]),
    ("media company",   ["media company", "newspaper", "magazine", "news agency",
                         "tv station", "television", "radio station", "broadcasting"],
                        ["office=media"]),

    # ── Retail ────────────────────────────────────────────────────────────────
    ("supermarket",     ["supermarket", "grocery store", "grocery shop", "food store",
                         "hypermarket", "mini mart"],
                        ["shop=supermarket", "shop=grocery"]),
    ("clothing store",  ["clothing", "fashion", "apparel", "boutique",
                         "clothes store", "garments", "fashion store"],
                        ["shop=clothes", "shop=fashion"]),
    ("electronics store", ["electronics", "tech store", "mobile shop", "computer shop",
                            "phone shop", "gadgets", "appliances"],
                          ["shop=electronics", "shop=computer", "shop=mobile_phone"]),
    ("furniture store", ["furniture", "furniture store", "home furniture",
                         "office furniture", "interior furniture"],
                        ["shop=furniture"]),
    ("toy store",       ["toy store", "toy shop", "toys", "kids store", "children store"],
                        ["shop=toys"]),
    ("jewelry store",   ["jewelry", "jewellery", "jeweler", "jeweller",
                         "jewelry store", "gold shop", "diamond store"],
                        ["shop=jewelry", "shop=jewellery"]),
    ("shoe store",      ["shoe store", "shoe shop", "footwear", "shoes",
                         "sneakers", "sandals store"],
                        ["shop=shoes"]),
    ("sports store",    ["sports store", "sports shop", "sports equipment",
                         "sporting goods", "outdoor gear", "fitness store"],
                        ["shop=sports"]),
    ("music store",     ["music store", "musical instruments", "guitar shop",
                         "music shop", "instrument store"],
                        ["shop=musical_instrument"]),
    ("bookstore",       ["bookstore", "bookshop", "book store", "book shop"],
                        ["shop=books"]),
    ("gift shop",       ["gift shop", "gift store", "souvenir", "souvenirs",
                         "novelty shop"],
                        ["shop=gift"]),
    ("pet shop",        ["pet shop", "pet store", "pet supplies", "animal store",
                         "aquarium shop"],
                        ["shop=pet"]),
    ("florist",         ["florist", "flower shop", "flower store", "flowers",
                         "flower delivery"],
                        ["shop=florist"]),
    ("garden center",   ["garden center", "garden centre", "plant nursery",
                         "plant shop", "garden supply"],
                        ["shop=garden_centre", "amenity=nursery"]),
    ("hardware store",  ["hardware store", "hardware shop", "tools", "building materials",
                         "construction supply", "diy store"],
                        ["shop=hardware", "shop=doityourself"]),
    ("stationery store", ["stationery", "office supplies", "paper shop", "art supplies",
                          "craft store"],
                         ["shop=stationery", "shop=art"]),
    ("optical store",   ["optical", "glasses", "spectacles", "eyewear shop",
                         "contact lenses", "sunglasses"],
                        ["shop=optician"]),
    ("bicycle shop",    ["bicycle shop", "bike shop", "cycling store", "bicycle repair",
                         "bike repair"],
                        ["shop=bicycle"]),
    ("antique shop",    ["antique", "antiques", "vintage shop", "thrift store",
                         "second hand", "used goods"],
                        ["shop=antiques", "shop=second_hand"]),
    ("pawn shop",       ["pawn shop", "pawnshop", "pawn broker"],
                        ["shop=pawnbroker"]),
    ("shopping mall",   ["shopping mall", "mall", "shopping center", "shopping centre",
                         "plaza", "shopping complex"],
                        ["shop=mall", "building=mall"]),
    ("market",          ["market", "bazaar", "bazar", "flea market", "farmers market",
                         "night market", "street market"],
                        ["amenity=marketplace", "landuse=retail"]),

    # ── Services ──────────────────────────────────────────────────────────────
    ("bank",            ["bank", "banks", "financial institution", "credit union",
                         "savings bank", "microfinance"],
                        ["amenity=bank"]),
    ("atm",             ["atm", "cash machine", "cash point"],
                        ["amenity=atm"]),
    ("money exchange",  ["money exchange", "currency exchange", "forex", "money changer"],
                        ["amenity=bureau_de_change"]),
    ("real estate",     ["real estate", "property agent", "estate agent", "realtor",
                         "property dealer", "property management"],
                        ["office=estate_agent"]),
    ("salon",           ["salon", "hair salon", "beauty salon", "barbershop",
                         "barber", "hair dresser", "hairdresser", "beauty parlour"],
                        ["shop=hairdresser", "shop=beauty"]),
    ("nail salon",      ["nail salon", "nail bar", "manicure", "pedicure",
                         "nail art", "nail studio"],
                        ["shop=nail_salon"]),
    ("tattoo parlor",   ["tattoo", "tattoo parlor", "tattoo parlour", "tattoo studio",
                         "piercing", "body art"],
                        ["shop=tattoo"]),
    ("gas station",     ["gas station", "petrol station", "fuel station",
                         "filling station", "service station", "petrol pump"],
                        ["amenity=fuel"]),
    ("car dealership",  ["car dealership", "car dealer", "auto dealer", "car showroom",
                         "vehicle dealer", "automobile dealer", "used cars"],
                        ["shop=car", "shop=car_dealer"]),
    ("car repair",      ["car repair", "auto repair", "garage", "mechanic",
                         "auto workshop", "car service", "vehicle repair", "auto shop"],
                        ["amenity=car_repair", "shop=car_repair"]),
    ("car wash",        ["car wash", "auto wash", "vehicle wash", "car cleaning"],
                        ["amenity=car_wash"]),
    ("car rental",      ["car rental", "car hire", "vehicle rental", "rent a car"],
                        ["amenity=car_rental"]),
    ("auto parts",      ["auto parts", "spare parts", "car parts", "vehicle parts",
                         "automotive parts"],
                        ["shop=car_parts", "shop=tyres"]),
    ("parking",         ["parking", "parking lot", "car park", "parking garage",
                         "parking facility"],
                        ["amenity=parking"]),
    ("laundry",         ["laundry", "launderette", "laundromat", "dry cleaner",
                         "dry cleaning", "washing service", "linen service"],
                        ["shop=laundry", "shop=dry_cleaning"]),
    ("tailor",          ["tailor", "tailoring", "seamstress", "alteration",
                         "dressmaker", "suit maker", "clothing alteration"],
                        ["shop=tailor"]),
    ("travel agency",   ["travel agency", "travel agent", "tour operator", "tour agency",
                         "tourism company", "holiday agent", "ticketing agency"],
                        ["shop=travel_agency", "office=travel_agent"]),
    ("photography studio", ["photography", "photo studio", "photographer",
                            "photography studio", "portrait studio"],
                           ["craft=photographer", "shop=photo"]),
    ("printing shop",   ["printing", "print shop", "copy center", "photocopy",
                         "printing press", "signage"],
                        ["shop=printing"]),
    ("event venue",     ["event venue", "banquet hall", "wedding hall", "conference hall",
                         "function hall", "party hall", "events center", "convention center",
                         "conference center", "convention centre", "wedding venue"],
                        ["amenity=events_venue", "amenity=conference_centre"]),
    ("shipping company", ["shipping", "courier", "freight", "logistics company",
                          "delivery company", "cargo", "freight forwarder"],
                         ["office=logistics"]),
    ("storage facility", ["storage", "self storage", "storage facility",
                          "warehouse", "storage unit"],
                         ["amenity=storage_rental"]),
    ("moving company",  ["moving company", "movers", "removal company",
                         "relocation company", "packers and movers"],
                        ["office=moving_company"]),
    ("cleaning service", ["cleaning service", "cleaning company", "maid service",
                          "janitorial", "housekeeping"],
                         ["office=cleaning"]),
    ("security company", ["security company", "security agency", "security guard",
                          "private security"],
                         ["office=security"]),
    ("funeral home",    ["funeral home", "funeral parlour", "funeral parlor",
                         "mortuary", "funeral director"],
                        ["amenity=funeral_home"]),
    ("internet cafe",   ["internet cafe", "cyber cafe", "internet shop",
                         "computer cafe", "gaming cafe"],
                        ["amenity=internet_cafe"]),
    ("post office",     ["post office", "postal service", "courier office"],
                        ["amenity=post_office"]),
    ("lottery",         ["lottery", "betting shop", "sportsbook", "gambling"],
                        ["amenity=gambling", "shop=lottery"]),
    ("recycling center", ["recycling", "recycling center", "scrap", "junk dealer"],
                         ["amenity=recycling"]),

    # ── Entertainment ─────────────────────────────────────────────────────────
    ("cinema",          ["cinema", "movie theater", "movie theatre", "film theater",
                         "multiplex", "imax", "drive-in cinema"],
                        ["amenity=cinema"]),
    ("theatre",         ["theatre", "theater", "performing arts", "drama theater",
                         "opera house", "amphitheatre", "playhouse"],
                        ["amenity=theatre"]),
    ("nightclub",       ["nightclub", "night club", "disco", "club", "dance club",
                         "dance bar"],
                        ["amenity=nightclub"]),
    ("casino",          ["casino", "gambling hall", "gaming club"],
                        ["amenity=casino"]),
    ("bowling alley",   ["bowling", "bowling alley", "bowling center",
                         "bowling lane"],
                        ["leisure=bowling_alley"]),
    ("ice rink",        ["ice rink", "ice skating", "skating rink", "ice skate"],
                        ["leisure=ice_rink"]),
    ("escape room",     ["escape room", "escape game", "puzzle room"],
                        ["leisure=escape_game"]),
    ("museum",          ["museum", "history museum", "science museum",
                         "art museum", "natural history museum"],
                        ["tourism=museum"]),
    ("art gallery",     ["art gallery", "gallery", "exhibition space",
                         "contemporary art"],
                        ["tourism=gallery"]),
    ("zoo",             ["zoo", "zoological park", "animal park", "safari park",
                         "petting zoo", "wildlife park"],
                        ["tourism=zoo"]),
    ("aquarium",        ["aquarium", "sea life center", "marine aquarium",
                         "ocean park"],
                        ["tourism=aquarium"]),
    ("stadium",         ["stadium", "sports stadium", "football stadium",
                         "cricket stadium", "sports ground", "arena"],
                        ["leisure=stadium", "leisure=sports_centre"]),
    ("golf course",     ["golf", "golf course", "golf club", "golf range",
                         "driving range", "mini golf", "miniature golf"],
                        ["leisure=golf_course", "leisure=miniature_golf"]),
    ("snooker club",    ["snooker", "billiards", "pool hall", "billiard club",
                         "snooker club"],
                        ["leisure=billiard_room"]),
    ("arcade",          ["arcade", "gaming center", "game center", "video games",
                         "amusement arcade", "gaming zone"],
                        ["leisure=amusement_arcade", "amenity=amusement_arcade"]),
    ("playland",        ["playland", "playlands", "play land", "play lands",
                         "play area", "play areas", "playing area",
                         "amusement park", "theme park",
                         "fun park", "funland", "funfair", "joyland",
                         "adventure park", "kids park", "water park",
                         "waterpark", "family entertainment", "indoor play",
                         "soft play", "trampoline park"],
                        ["tourism=theme_park", "leisure=amusement_arcade",
                         "leisure=playground", "leisure=water_park"]),
    ("swimming pool",   ["swimming pool", "public pool", "aquatic center",
                         "swim club", "community pool"],
                        ["leisure=swimming_pool"]),
    ("tennis club",     ["tennis", "tennis club", "tennis court", "squash club"],
                        ["sport=tennis", "leisure=sports_centre"]),
    ("cricket club",    ["cricket", "cricket club", "cricket ground"],
                        ["sport=cricket"]),
    ("football club",   ["football club", "soccer club", "football team",
                         "football ground"],
                        ["sport=football"]),
    ("sports club",     ["sports club", "athletic club", "athletics"],
                        ["leisure=sports_centre", "leisure=pitch"]),
    ("paintball",       ["paintball", "laser tag", "airsoft"],
                        ["leisure=miniature_golf"]),

    # ── Hospitality & Tourism ─────────────────────────────────────────────────
    ("park",            ["park", "national park", "botanical garden", "public garden",
                         "nature reserve", "wildlife sanctuary"],
                        ["leisure=park", "leisure=nature_reserve", "leisure=garden"]),

    # ── Religious ─────────────────────────────────────────────────────────────
    ("mosque",          ["mosque", "masjid", "islamic center", "islamic centre",
                         "muslim prayer hall", "jama masjid"],
                        ["amenity=place_of_worship"]),
    ("church",          ["church", "cathedral", "chapel", "christian church",
                         "parish", "basilica"],
                        ["amenity=place_of_worship"]),
    ("temple",          ["temple", "hindu temple", "mandir", "shrine",
                         "buddhist temple", "pagoda", "wat"],
                        ["amenity=place_of_worship"]),
    ("synagogue",       ["synagogue", "jewish temple", "jewish center"],
                        ["amenity=place_of_worship"]),
    ("gurdwara",        ["gurdwara", "sikh temple", "sikh center"],
                        ["amenity=place_of_worship"]),

    # ── Manufacturing & Industrial ────────────────────────────────────────────
    ("factory",         ["factory", "manufacturing plant", "production facility",
                         "industrial unit", "mill", "plant"],
                        ["man_made=works", "landuse=industrial"]),
    ("logistics",       ["logistics", "warehouse", "distribution center",
                         "fulfillment center", "supply chain"],
                        ["office=logistics", "building=warehouse"]),

    # ── Agriculture ───────────────────────────────────────────────────────────
    ("farm",            ["farm", "dairy farm", "poultry farm", "fish farm",
                         "agricultural farm"],
                        ["landuse=farmland", "building=farm"]),
    ("agricultural supply", ["agricultural supply", "agri supply", "fertilizer shop",
                             "seed store", "farm supply"],
                            ["shop=agrarian"]),

    # ── Trades / Crafts ───────────────────────────────────────────────────────
    ("plumber",         ["plumber", "plumbing", "pipe fitting", "plumbing service"],
                        ["craft=plumber"]),
    ("electrician",     ["electrician", "electrical contractor", "electrical service",
                         "wiring service"],
                        ["craft=electrician"]),
    ("carpenter",       ["carpenter", "carpentry", "woodwork", "joiner",
                         "furniture maker"],
                        ["craft=carpenter"]),
    ("painter",         ["painter", "painting contractor", "house painter",
                         "painting service", "decorator"],
                        ["craft=painter"]),
    ("construction",    ["construction", "contractor", "builder", "building contractor",
                         "construction company"],
                        ["office=construction"]),
]


@dataclass
class ParsedQuery:
    raw_query: str
    entity_type: str
    location: str
    keywords: List[str] = field(default_factory=list)
    osm_tags: List[str] = field(default_factory=list)

    def search_queries(self) -> List[str]:
        queries = [
            f'{self.entity_type} in {self.location}',
            f'best {self.entity_type} {self.location}',
        ]
        if self.keywords:
            queries.append(f'{self.keywords[0]} {self.location} contact')
        return queries


_IN_PATTERN = re.compile(
    r"\b(?:in|at|near|around|from|within)\s+(.+)$", re.IGNORECASE
)


def _extract_location(query: str) -> tuple[str, str]:
    m = _IN_PATTERN.search(query)
    if m:
        location = m.group(1).strip()
        entity_part = query[: m.start()].strip()
        return entity_part, location
    if "," in query:
        parts = [p.strip() for p in query.split(",", 1)]
        return parts[0], parts[1]
    return query.strip(), ""


def _stem_word(w: str) -> str:
    """Strip plural suffix from a single word: galleries→gallery, parks→park."""
    if len(w) > 5 and w.endswith("ies"):
        return w[:-3] + "y"
    if len(w) > 5 and w.endswith("es") and not w.endswith("ses"):
        return w[:-2]
    if len(w) > 4 and w.endswith("s") and not w.endswith("ss"):
        return w[:-1]
    return w


def _match_entity(entity_part: str) -> tuple[str, list, list]:
    ep_lower = entity_part.lower()
    # Also try with each word stemmed so "art galleries" → "art gallery"
    ep_stemmed = " ".join(_stem_word(w) for w in ep_lower.split())
    # Prefer the LONGEST matching keyword so "driving school" beats "school",
    # and "snooker" (7) beats "club" (4) from the nightclub entry.
    best: tuple[str, list, list] | None = None
    best_len = 0
    for canonical, kws, tags in ENTITY_TYPES:
        for kw in kws:
            if (kw in ep_lower or kw in ep_stemmed) and len(kw) > best_len:
                best = (canonical, kws, tags)
                best_len = len(kw)
    if best:
        return best
    words = ep_lower.split()
    return ep_lower, words, []


def parse_query(raw_query: str) -> ParsedQuery:
    entity_part, location = _extract_location(raw_query.strip())
    canonical, keywords, osm_tags = _match_entity(entity_part)

    return ParsedQuery(
        raw_query=raw_query,
        entity_type=canonical,
        location=location or entity_part,
        keywords=keywords,
        osm_tags=osm_tags,
    )
